### ISSUE TITLE
Monitor uses IPv6 or IPv4

### ISSUE THREAD

**Issue by ON5HB** [ntppool/monitor#2]
I would suggest you include the type of monitor in the API-Key so your server knows it handles IPv6 or IPv4.
That way IPv4 monitors won't try to test IPv6 servers.

Just a suggestion.

**Comment by abh** [comment]
Hi @ON5HB -- the API server assigns work according to how the monitor was registered. I think back in May you saw a bug when the management UI setup some of the servers wrong!
